from robot_control import RobotControl
import time

rc = RobotControl()
time.sleep(1)
#rc.setDepth(0.4)
rc.setHeading(75)
rc.forwardDist(3, 3)
deg = rc.return_compass()
print(deg)
#rc.forwardHeading(3, 6)
#rc.setHeading(90+deg)
#rc.forwardHeading(3, 3.5)
#rc.setHeading(180+deg)
#rc.forwardHeading(3, 3.5)
#rc.setHeading(270+deg)
#rc.forwardHeading(3, 3.5)
#rc.setHeading(88)
#rc.movement(throttle=0, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=2)
#rc.setHeading(178)
#rc.movement(throttle=0, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=2)
#rc.setHeading(268)
#rc.movement(throttle=0, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=2)
#rc.setHeading(358)
#rc.movement(throttle=0, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=2)
#rc.setHeading(88)

#rc.setHeading(20)
#rc.movement(throttle=0, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=3)
#rc.movement(throttle=-18.75, forward=3, lateral=0, yaw=0, pitch=0, roll=0, t=4)
#rc.movement(throttle=0, forward=0, lateral=2, yaw=0, pitch=0, roll=0, t=3)
#rc.movement(throttle=0, forward=-2, lateral=0, yaw=0, pitch=0, roll=0, t=3)
#rc.movement(throttle=0, forward=0, lateral=-2, yaw=0, pitch=0, roll=0, t=3)
print("finished")
