version: 1
disable_existing_loggers: True

formatters:
    my_std:
        format: "%(asctime)s [%(name)s][%(levelname)s] %(message)s"
        datefmt: "%Y/%m/%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: my_std
        level: DEBUG
        stream: ext://sys.stdout

loggers:
    __main__:
        level: DEBUG
        handlers: [console]
        propagate: no
    rosout:
        level: INFO
        propagate: yes
        qualname: rosout

root:
    level: INFO
    handlers: [console]
    # handlers: [console, info_file_handler]