sudo: false
language: python
python:
- '2.7'
- '3.6'
install: pip install coverage python-coveralls pytest pytest-flakes pytest-cov pytest-random
script:
- python setup.py develop
- coverage run -m pytest wlmodem
- coverage report -m
after_success:
- coveralls
deploy:
  provider: pypi
  user: waterlinked
  password:
    secure: MeT7OgvCjW3g9ryClZjLNVgT5XZca55Lx7ltF+fRL+125vWpLhQIWRA8ySP9WHC0BBIDXbzTzt6lOIXCdlGea89D/uBHJZa+uXD7aEvVaBxWfyyKP7q8MDdNuMyAycIn0SGGAXJJpJqURgW1eW0ZlnifLDFCvvvt7kIslYYfyBauIsHF6fcRqiCUCrNr6jfAbXxKCiCzuWcef4k0+BWyakp7CdQnyGEl9S9+eEHbJ2ZCk6uasn60lTzDoa486E7rQC9YszKSQRC4R24ij/H7Q+cwcHhyJHAIR+K+9gGQvd3PWVsGl+XxlTOuZRp/GF4fLaEyOOg/kcGUr602C733QjxhpYCvsqsYTgV8/9HLyRmV+wPpck26dlgtZqCyV50K2MiHcogDJGcnJwUT2rYjj2afZBz0300gKkmWZs85BR/O9TC+XMJHTuy+kdkB0oFCcluknajKNod+a1uNR4HWcuKar7ILPFR1/X98njR+3/SCJUVxZ0U8pH+/yDffLnMkdqN239C6/0/CsJiHRDXF5UpukZfv4dG95atOdAQDEzAZ4RYQPs5jb+usUD1TWuAMNe7cD9eFPF3hoK+SGxvDmsEoIz4wzcDQVmljrgNvlPzLQANEWOkg7LQa0KsbxQzF/HSwfJfzAgGEHw+7PfzZ/49j+Vlvurakyv+NxpO475U=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
